coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/test-data.ts"
  - "**/setup.ts"
  - "**/__tests__/**"
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"
